{{- if and .Values.wordpress.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "custom-wordpress.fullname" . }}-wp
  labels:
    {{- include "custom-wordpress.labels" . | nindent 4 }}
spec:
  accessModes:
    {{- toYaml .Values.wordpress.persistence.accessModes | nindent 4 }}
  resources:
    requests:
      storage: {{ .Values.wordpress.persistence.size | quote }}
  {{- if .Values.wordpress.persistence.storageClassName }}
  storageClassName: {{ .Values.wordpress.persistence.storageClassName | quote }}
  {{- end }}
{{- end }}
