{{- if and .Values.auth.create (not .Values.auth.existingSecret) }}
{{- $secretName := include "custom-wordpress.secretName" . -}}
{{- $existing := (lookup "v1" "Secret" .Release.Namespace $secretName) -}}

{{- $root := default "" .Values.auth.mysqlRootPassword -}}
{{- $wpPass := default "" .Values.auth.wordpressPassword -}}
{{- $wpDb := default "wordpress" .Values.auth.wordpressDatabase -}}
{{- $wpUser := default "wordpress" .Values.auth.wordpressUser -}}

{{- if and (eq $root "") $existing }}
{{- $root = (index $existing.data "mysql-root-password" | b64dec) -}}
{{- else if eq $root "" }}
{{- $root = randAlphaNum 20 -}}
{{- end }}

{{- if and (eq $wpPass "") $existing }}
{{- $wpPass = (index $existing.data "wordpress-password" | b64dec) -}}
{{- else if eq $wpPass "" }}
{{- $wpPass = randAlphaNum 20 -}}
{{- end }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  labels:
    {{- include "custom-wordpress.labels" . | nindent 4 }}
type: Opaque
stringData:
  mysql-root-password: {{ $root | quote }}
  wordpress-db: {{ $wpDb | quote }}
  wordpress-user: {{ $wpUser | quote }}
  wordpress-password: {{ $wpPass | quote }}
{{- end }}
