apiVersion: v1
kind: Service
metadata:
  name: {{ include "custom-wordpress.fullname" . }}
  labels:
    {{- include "custom-wordpress.labels" . | nindent 4 }}
spec:
  type: {{ .Values.wordpress.service.type }}
  ports:
    - name: http
      port: {{ .Values.wordpress.service.port }}
      targetPort: http
  selector:
    {{- include "custom-wordpress.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: wordpress
